config/routes.rb
Rails.application.routes.draw do

  resources :employees do
    get '(page/:page)', action: :index, on: :collection
  end
  
  get 'getting_data_for_api', to: "employees#getting_data_for_api"
  root to: 'employees#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  paginates_per 12

  validates :email, :firstname, :lastname, presence: true

  def full_name
    "#{self.title} #{self.firstname} #{self.lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[edit update destroy]
  before_action :set_employees_for_api, only: %i[getting_data_for_api]

  def index
    @employees = Employee.order(id: :desc).page(params[:page])
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.avatar = params[:file] if params[:file]
    if @employee.save
      redirect_to employees_path, notice: "Employee was created successfully"
    else
      render :new
    end
  end

  def update
    @employee.avatar = params[:file] if params[:file]
    if @employee.update(employee_params)
      redirect_to employees_path, notice: "Employee was successfully updated"
    else
      render :edit
    end
  end

  # Action for add data from the external API
  def getting_data_for_api
    @array_employees.each do |employee|
      new_employee = Employee.new(
        title: employee['name']['title'],
        firstname: employee['name']['first'],
        lastname: employee['name']['last'],
        email: employee['email'],
        gender: employee['gender'],
      )
      new_employee.remote_avatar_url = employee['picture']['large']
      new_employee.save!
    end

    redirect_to root_path, notice: "Data was saved successfully"
  end

  def destroy
    @employee.remove_avatar! if @employee.avatar? # To destroy the picture from employee
    if @employee.destroy
      redirect_to employees_path, notice: "Employee was successfully destroyed."
    else
      redirect_to employees_path, error: "There's no employee with this id"
    end
  end

  private

  # GET the data from the external api
  def set_employees_for_api
    resp = RestClient.get("https://randomuser.me/api?format=json&results=30&inc=gender,name,email,picture&nat=br&seed=giga")
    @array_employees = JSON.parse(resp.body)["results"]
  end

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:title, :firstname, :lastname, :email, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-sm-2'>
      <div class='form-group'>
        <%= form.label :title %>
        <%= form.select :title, options_for_select(["Mr", "Miss"]), {}, {class:"custom-select"} %>
      </div>
    </div>
    <div class='col-sm-3'>
      <div class='form-group'>
        <%= form.label :firstname %>
        <%= form.text_field :firstname, class:"form-control" %>
      </div>
    </div>
    <div class='col-sm-3'>
      <div class='form-group'>
        <%= form.label :lastname %>
        <%= form.text_field :lastname, class:"form-control" %>
      </div>
    </div>
    <div class='col-sm-4'>
      <div class='form-group'>
        <%= form.label :email %>
        <%= form.email_field :email, class:"form-control", placeholder:"example@gmail.com" %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-sm-6'>
      <div class='form-group'>
        <%= form.label :gender %>
        <%= form.select :gender, options_for_select(["Male", "Female"]), {}, {class:"custom-select"} %>
      </div>
    </div>
    <div class='col-sm-6'>
      <div class='form-group'>
        <div class='custom-file' style='margin-top: 32px;'>
          <%= form.file_field :avatar, class:"custom-file-input", id:"customFile" %>
          <%= form.label :choose_picture, class:"custom-file-label", id:"customFileLang" %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Save", class:"btn btn-primary" %>
    <%= link_to 'Back', employees_path, class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class='container'>
  <div class='card'>
    <div class='card-body'>
      <h3 class='h3'>Editing Employee</h3>

      <%= render 'form', employee: @employee %>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class='container'>
  <div class='row'>
    <% @employees.each do |employee| %>
      <div class='col-sm-4'>
        <div class='card border-dark mb-3'>
          <div class='card-header text-center bg-dark text-white'>
            <nav class='navbar navbar-dark bg-dark'>
              <div class="navbar-brand mb-0 h1 text-white">
                <%= employee.full_name.truncate(20) %>
              </div>
              
              <div class='nav-item'>
                <%= link_to edit_employee_path(employee), class:"text-white" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pen-fill" viewBox="0 0 16 16">
                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001z"/>
                  </svg>
                <% end %>

                <%= link_to employee_path(employee), method: :delete, data: { confirm: "Are you sure ?"}, class:"text-white" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"/>
                  </svg>
                <% end %>
              </div>
            </nav>
            
          </div>
          <div class='card-body'>
            <div class='container'>
              <div class='employee'>
                <%= employee.avatar? ? image_tag(employee.avatar.large.url, class:'img-profile') : image_tag("https://via.placeholder.com/128C", class:'img-profile') %>
                  <span>
                    <label><strong>Gender: </strong></label> <%= employee.gender %>
                  </span>
                  <label><strong>Email: </strong></label>
                  <%= employee.email %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class='container'>
  <div class='pagination'>
    <%= paginate @employees %>
  </div>
</div>

app/views/employees/new.html.erb
<div class='container'>
  <div class='card'>
    <div class='card-body'>
      <h1 class='h3'>New Employee</h1>

      <%= render 'form', employee: @employee %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employees System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand mb-0 h1 text-white" href="/">
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
          <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
          <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
      </span>
      Employees List
    </a>
  </div>

  <div class='nav-item'>
    <%= link_to getting_data_for_api_path, class:"btn btn-outline-light" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cloud-download" viewBox="0 0 16 16">
        <path d="M4.406 1.342A5.53 5.53 0 0 1 8 0c2.69 0 4.923 2 5.166 4.579C14.758 4.804 16 6.137 16 7.773 16 9.569 14.502 11 12.687 11H10a.5.5 0 0 1 0-1h2.688C13.979 10 15 8.988 15 7.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 2.825 10.328 1 8 1a4.53 4.53 0 0 0-2.941 1.1c-.757.652-1.153 1.438-1.153 2.055v.448l-.445.049C2.064 4.805 1 5.952 1 7.318 1 8.785 2.23 10 3.781 10H6a.5.5 0 0 1 0 1H3.781C1.708 11 0 9.366 0 7.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383z"/>
        <path d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
      </svg>
    <% end %>
  </div>&nbsp;
  
  <div class='nav-item'>
    <%= link_to new_employee_path, class:"btn btn-outline-light" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
        <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
        <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
      </svg>
    <% end %>
  </div>
</nav><br>